import { TheGathering } from './encounterData'

export const CardDecks = [
    {
        id: 1,
        name: 'Roland Banks Deck',
        deck: [
            {
                category: 'player',
                type: 'Asset',
                url: 'guardian',
                image: '1-3.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'guardian',
                image: '2-3.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'guardian',
                image: '2-3.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'guardian',
                image: '5-3.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'guardian',
                image: '5-3.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'guardian',
                image: '6.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'guardian',
                image: '6.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'guardian',
                image: '7.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'guardian',
                image: '7.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'guardian',
                image: '8.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'guardian',
                image: '8.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'guardian',
                image: '9.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'guardian',
                image: '10.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'guardian',
                image: '10.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'seeker',
                image: '8s.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'seeker',
                image: '8s.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'seeker',
                image: '10s.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'seeker',
                image: '10s.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'neutral',
                image: 'n1.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'neutral',
                image: 'n1.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'neutral',
                image: 'n2.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'neutral',
                image: 'n2.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'neutral',
                image: 'n3.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'neutral',
                image: 'n3.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'neutral',
                image: 'n4.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'neutral',
                image: 'n4.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'neutral',
                image: 'n6.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'neutral',
                image: 'n6.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'neutral',
                image: 'n8.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'neutral',
                image: 'n8.webp',
            },
        ],
    },
    {
        id: 2,
        name: 'Daisy Walker Deck',
        deck: [
            {
                category: 'player',
                type: 'Asset',
                url: 'seeker',
                image: '1s.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'seeker',
                image: '1s.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'seeker',
                image: '2s.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'seeker',
                image: '2s.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'seeker',
                image: '3s.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'seeker',
                image: '4s.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'seeker',
                image: '4s.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'seeker',
                image: '6s.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'seeker',
                image: '7s.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'seeker',
                image: '7s.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'seeker',
                image: '8s.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'seeker',
                image: '8s.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'seeker',
                image: '10s.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'seeker',
                image: '10s.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'mystic',
                image: 'm2.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'mystic',
                image: 'm2.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'mystic',
                image: 'm3.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'mystic',
                image: 'm3.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'mystic',
                image: 'm4.webp',
            },
            {
                category: 'player',
                type: 'Asset',
                url: 'mystic',
                image: 'm4.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'mystic',
                image: 'm8.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'mystic',
                image: 'm8.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'mystic',
                image: 'm9.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'mystic',
                image: 'm9.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'mystic',
                image: 'm10.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'mystic',
                image: 'm10.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'neutral',
                image: 'n3.webp',
            },
            {
                category: 'player',
                type: 'Event',
                url: 'neutral',
                image: 'n3.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'neutral',
                image: 'n7.webp',
            },
            {
                category: 'player',
                type: 'Skill',
                url: 'neutral',
                image: 'n7.webp',
            },
        ],
    },
]

export const WeaknessDeck: DeckCard[] = [
    {
        category: 'player',
        type: 'Treachery',
        url: 'weakness',
        image: 'w1.webp',
    },
    {
        category: 'player',
        type: 'Treachery',
        url: 'weakness',
        image: 'w2.webp',
    },
    {
        category: 'player',
        type: 'Treachery',
        url: 'weakness',
        image: 'w3.webp',
    },
    {
        category: 'player',
        type: 'Treachery',
        url: 'weakness',
        image: 'w4.webp',
    },
    {
        category: 'player',
        type: 'Treachery',
        url: 'weakness',
        image: 'w5.webp',
    },
    {
        category: 'player',
        type: 'Event',
        url: 'weakness',
        image: 'w6.webp',
    },
    {
        category: 'player',
        type: 'Event',
        url: 'weakness',
        image: 'w7.webp',
    },
    {
        category: 'player',
        type: 'Event',
        url: 'weakness',
        image: 'w8.webp',
    },
]

export const PlayerCards = WeaknessDeck.concat(
    CardDecks[0].deck as DeckCard[]
).concat(CardDecks[1].deck as DeckCard[])

export const EncounterCards = TheGathering
