import {
    AncientEvils,
    ChillingCold,
    Ghouls,
    Rats,
    StrikingFear,
    TheGathering,
} from './encounterData'

export const DaisyDeck = [
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: 'daisy3.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: 'daisy4.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: '1s.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: '1s.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: '2s.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: '2s.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: '3s.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: '4s.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: '4s.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'seeker',
        image: '6s.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'seeker',
        image: '7s.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'seeker',
        image: '7s.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'seeker',
        image: '8s.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'seeker',
        image: '8s.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'seeker',
        image: '10s.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'seeker',
        image: '10s.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'mystic',
        image: 'm2.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'mystic',
        image: 'm2.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'mystic',
        image: 'm3.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'mystic',
        image: 'm3.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'mystic',
        image: 'm4.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'mystic',
        image: 'm4.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'mystic',
        image: 'm8.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'mystic',
        image: 'm8.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'mystic',
        image: 'm9.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'mystic',
        image: 'm9.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'mystic',
        image: 'm10.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'mystic',
        image: 'm10.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'neutral',
        image: 'n3.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'neutral',
        image: 'n3.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'neutral',
        image: 'n7.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'neutral',
        image: 'n7.webp',
    },
]

export const RolandDeck = [
    {
        category: 'player',
        type: 'asset',
        url: 'guardian',
        image: 'roland3.webp',
    },
    {
        category: 'player',
        type: 'treachery',
        url: 'guardian',
        image: 'roland4.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'guardian',
        image: '1-3.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'guardian',
        image: '2-3.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'guardian',
        image: '2-3.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'guardian',
        image: '5-3.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'guardian',
        image: '5-3.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'guardian',
        image: '6.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'guardian',
        image: '6.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'guardian',
        image: '7.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'guardian',
        image: '7.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'guardian',
        image: '8.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'guardian',
        image: '8.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'guardian',
        image: '9.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'guardian',
        image: '10.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'guardian',
        image: '10.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'seeker',
        image: '8s.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'seeker',
        image: '8s.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'seeker',
        image: '10s.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'seeker',
        image: '10s.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'neutral',
        image: 'n1.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'neutral',
        image: 'n1.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'neutral',
        image: 'n2.webp',
    },
    {
        category: 'player',
        type: 'asset',
        url: 'neutral',
        image: 'n2.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'neutral',
        image: 'n3.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'neutral',
        image: 'n3.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'neutral',
        image: 'n4.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'neutral',
        image: 'n4.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'neutral',
        image: 'n6.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'neutral',
        image: 'n6.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'neutral',
        image: 'n8.webp',
    },
    {
        category: 'player',
        type: 'skill',
        url: 'neutral',
        image: 'n8.webp',
    },
]

export const WeaknessDeck = [
    {
        category: 'player',
        type: 'treachery',
        url: 'weakness',
        image: 'w1.webp',
    },
    {
        category: 'player',
        type: 'treachery',
        url: 'weakness',
        image: 'w2.webp',
    },
    {
        category: 'player',
        type: 'treachery',
        url: 'weakness',
        image: 'w3.webp',
    },
    {
        category: 'player',
        type: 'treachery',
        url: 'weakness',
        image: 'w4.webp',
    },
    {
        category: 'player',
        type: 'treachery',
        url: 'weakness',
        image: 'w5.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'weakness',
        image: 'w6.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'weakness',
        image: 'w7.webp',
    },
    {
        category: 'player',
        type: 'event',
        url: 'weakness',
        image: 'w8.webp',
    },
]

export const PlayerCards = RolandDeck.concat(DaisyDeck).concat(WeaknessDeck)

export const EncounterCards = TheGathering
